# Generated by Django 5.2.8 on 2025-11-20 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.cuisinetype'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'restaurant')},
        ),
    ]
